spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/baby_doge_paws
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: baby-doge-paws-datasource
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
baby-doge-paws:
  chrome:
    root-data-dir: D:\chrome-user-data\
  bootstrap:
    - 19962006575
    - 8502950634