spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.37.17:3306/baby_doge_paws
    username: root
    password: Zyc3.1415926
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: baby-doge-paws-datasource
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
baby-doge-paws:
  chrome:
    root-data-dir: E:\chrome-user-data\
  bootstrap: true